#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl12, greenLight,     sensorLEDtoVCC)
#pragma config(Motor,  port2,           flashLeft,     tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port3,           backLMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           steering,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           backRMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lightSpin,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flashRight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DETECTION_THRESHOLD 250
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive();
void steer();
void toggleFlash();
void spinLight();
void blinkLED();


task main() {

	int ambientLightValue = SensorValue(lightSensor);
	while (1 == 1) {
		turnLEDOff(greenLight);

		//condition works during day and night
		if (abs(ambientLightValue - SensorValue(lightSensor)) >= DETECTION_THRESHOLD) {
			blinkLED();
			break;
		}

		toggleFlash();
		drive();
		steer();
		spinLight();
	}
}

void drive() {
	//when button 6D pressed, drive forward
	if (vexRT[Btn6D] == 1) {
		motor[backLMotor] = -127;
		motor[backRMotor] = 127;
	}

	//when button 6U pressed, drive backward
	else if (vexRT[Btn6U] == 1) {
		motor[backLMotor] = 127;
		motor[backRMotor] = -127;
	}

	//if no button pressed, stop
	else {
		motor[backLMotor] = 0;
		motor[backRMotor] = 0;
	}
	//writeDebugStream("backLMotor: %d, backRMotor: %d\n", motor[backLMotor], motor[backRMotor]);
}

void steer() {
	//motor[steering] = -vexRT[Ch4];
	setServo(steering, vexRT[Ch4]);
	//writeDebugStream("steering: %d", vexRT[Ch4]);
}

void spinLight() {
	int counter = 0;
	if (vexRT[Btn8L] == 1) {
		counter--;
		if (counter <= -4) {
			return;
		}
		else {
			motor[lightSpin] = -12;
			wait(0.5);
			motor[lightSpin] = 0;
		}
	}

	else if (vexRT[Btn8R] == 1) {
		counter++;
		if (counter >= 4) {
			return;
		}
		else {
			motor[lightSpin] = 12;
			wait(0.5);
			motor[lightSpin] = 0;
		}
	}
}

void toggleFlash() {
	if (vexRT[Btn5U] == 1) {
		turnFlashlightOn(flashLeft);
		turnFlashlightOn(flashRight);
	}

	else if (vexRT[Btn5D] == 1) {
		turnFlashlightOff(flashLeft);
		turnFlashlightOff(flashRight);
	}
}


void blinkLED() {
	for (int i = 0; i < 100; i++) {
		turnLEDOn(greenLight);
		wait(0.05);
		turnLEDOff(greenLight);
		wait(0.05);
	}
}
